### ISSUE TITLE
rsdmx package for R

### ISSUE THREAD

**Issue by eblondel** [ropensci/onboarding#15]
- 1. What does this package do? (explain in 50 words or less)

`rsdmx` is a package to parse/read SDMX data and metadata documents in R. It provides a set of classes and methods to read data and metadata documents exchanged through the Statistical Data and Metadata Exchange (SDMX) framework. The package currently focuses on the SDMX XML standard format (SDMX-ML). It is part of the Web Technologies CRAN Task View. [More details](https://github.com/opensdmx/rsdmx/wiki#package_overview).
- 2. Paste the full DESCRIPTION file inside a code block (bounded by ``` on either end).

```
Package: rsdmx
Version: 0.4-7
Date: 2015-06-01
Title: Tools for Reading SDMX Data and Metadata
Authors@R: c(
  person("Emmanuel", "Blondel", role = c("aut", "cre"), email = "emmanuel.blondel1@gmail.com"),
  person("Matthieu", "Stigler", role = c("ctb")))
Maintainer: Emmanuel Blondel <emmanuel.blondel1@gmail.com>
Depends: R (>= 2.15)
Imports: methods, XML (>= 3.96-1.1), RCurl, plyr
Suggests: testthat
Description: Set of classes and methods to read data and metadata documents
  exchanged through the Statistical Data and Metadata Exchange (SDMX) framework,
  currently focusing on the SDMX XML standard format (SDMX-ML).
License: GPL (>= 2)
URL: https://github.com/opensdmx/rsdmx, http://www.sdmx.org
BugReports: https://github.com/opensdmx/rsdmx/issues
LazyLoad: yes
Collate:
  Class-SDMXSchema.R Class-SDMXType.R Class-SDMXStructureType.R
  Class-SDMXHeader.R Class-SDMXFooterMessage.R Class-SDMXFooter.R
  Class-SDMX.R Class-SDMXGenericData.R Class-SDMXCompactData.R Class-SDMXUtilityData.R
  Class-SDMXMessageGroup.R Class-SDMXConcept.R Class-SDMXConceptScheme.R Class-SDMXConcepts.R
  Class-SDMXCode.R Class-SDMXCodelist.R Class-SDMXCodelists.R Class-SDMXDimension.R
  Class-SDMXTimeDimension.R Class-SDMXPrimaryMeasure.R Class-SDMXAttribute.R Class-SDMXComponents.R
  Class-SDMXDataStructure.R Class-SDMXDataStructures.R Class-SDMXDataStructureDefinition.R
  SDMXSchema-methods.R SDMXType-methods.R SDMXStructureType-methods.R SDMXHeader-methods.R
  SDMXFooterMessage-methods.R SDMXFooter-methods.R SDMX-methods.R
  SDMXGenericData-methods.R SDMXCompactData-methods.R SDMXUtilityData-methods.R SDMXMessageGroup-methods.R
  SDMXConcept-methods.R SDMXConceptScheme-methods.R SDMXConcepts-methods.R SDMXCode-methods.R
  SDMXCodelist-methods.R SDMXCodelists-methods.R SDMXDimension-methods.R SDMXTimeDimension-methods.R
  SDMXPrimaryMeasure-methods.R SDMXAttribute-methods.R SDMXComponents-methods.R
  SDMXDataStructure-methods.R SDMXDataStructures-methods.R SDMXDataStructureDefinition-methods.R
  readSDMX.R
```
- 3. URL for the package (the development repository, not a stylized html page)

[https://github.com/opensdmx/rsdmx](https://github.com/opensdmx/rsdmx)
- 4. What data source(s) does it work with (if applicable)?

All SDMX-ML standard compliant data sources, supporting SDMX-ML format version `1.0`, `2.0` and `2.1`. Notice that a development strategy of `rsdmx` is to follow a low-level approach which intends to focus on the SDMX `format` specification, rather than the SDMX `web-service` specifications. `rsdmx` is then not restricted to the web (SDMX local files can be read) and for the web, it is not restricted to data sources disseminated with web-services compliant with the SDMX web-service specifications.
- 5. Who is the target audience?

Universities, Research scientists, statisticians, public institutions & companies that need to extract statistical data in R from institutions that disseminate data and metadata in the Statistical Data and Metadata eXchange format (SDMX).
- 6. Are there other R packages that accomplish the same thing? If so, what is different about yours?

As known active package, `RJSDMX` provides an interface to read SDMX data in R. AFAIK, the main differences i've identified are: (1) the core technology to read SDMX documents (`rsdmx` is writen in R and relies on the `XML` package, `RJSDMX` builds on a Java statistical software connector.), (2) `RJSDMX` restrains to SDMX data exchanged with known web-services strictly complying with the SDMX web-service standards, while `rsdmx` starts from a lower level flexible approach, focusing only on the SDMX _format_ specification (See above point 4.). As consequence, `rsdmx` does not bring (at now) helpers to "build" the SDMX web requests, but allows to read both local and remote SDMX data (from standard web-service architectures or not) and makes abstraction of the data providers and the data domain.
- 7. Check the box next to each policy below, confirming that you agree. These are mandatory.
- [X] This package does not violate the Terms of Service of any service it interacts with.
- [X] The repository has continuous integration with Travis and/or another service
- [X] The package contains a vignette **(An online documentation is available and continuously updated. And i've added a quickstart vignette based on it.)**
- [X] The package contains a reasonably complete readme with devtools install instructions
- [X] The package contains unit tests
- [X] The package only exports functions to the NAMESPACE that are intended for end users
- 8. Do you agree to follow the [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? These aren't mandatory, but we strongly suggest you follow them. If you disagree with anything, please explain.
- [ ] Are there any package dependencies not on CRAN?
- [ ] Do you intend for this package to go on CRAN? **(yet on CRAN)**
- [X] Does the package have a CRAN accepted license?
- [ ] Did `devtools::check()` produce any errors or warnings? If so paste them below.
- 9. Please add explanations below for any exceptions to the above:
- 10. If this is a resubmission following rejection, please explain the change in cirucmstances.

**Comment by karthik** [comment]
Thanks Emmanuel, we'll follow up soon.

**Comment by karthik** [comment]
Package is being reviewed by @jeroenooms

**Comment by jeroenooms** [comment]
Thanks for this submission, Emmanuel!

I've been browsing through the code and documentation (which look good) but I am having difficulty wrapping my head around what the purpose of the sdmx format is, how it compares to other data formats, and how your package maps sdmx data to data frames in R. 

I tried to compile the quickstart vignette but it gets stuck at the line

```r
stats <- as.data.frame(sdmx)
```

Also the vignette is still pretty technical and assumes the user is familiar with the sdmx format. I had never heard of this format before and the website isn't too helpful either so you'll have to help us a bit.

It would be very helpful to include a high-level vignette that introduces the main ideas from the sdmx format using worked examples with `rsdmx`. You don't have to discuss S4 classes or implementation details, those are sufficiently documented. The challenge is show some nice examples that illustrate in a few minutes what the sdmx format is used for and how your package makes it easy to access these data from R. Your readme lists a dozen of sdmx data sources, so it would be great if we can see the package in action on real-world data. Maybe you already have these examples and I just couldn't find them, in that case just put them in a nice vignette.

The jsonlite package has a few vignettes that illustrate the [mapping](http://cran.r-project.org/web/packages/jsonlite/vignettes/json-aaquickstart.html) and one with [web api examples](http://cran.r-project.org/web/packages/jsonlite/vignettes/json-apis.html). Something similar for sdmx would be very helpful to help the user get started with sdmx and rsdmx.

**Comment by eblondel** [comment]
Hello,

The SDMX format is a standard for data and metadata exchange between institutions. I'm not a SDMX data provider, so i cannot argue more for the SDMX format than other, but i know it is widely used by institutions that want to disseminate statistics, timeseries, whatever the domain. One benefit of SDMX is to bring with a dataset its complete data structure, named ``data structure definition`` in the SDMX vocabulary (metadata).

There is a good summary introduction to SDMX and their web-services [here](http://rbagd.eu/2015-03-28/downloading-data-with-sdmx-protocol-from-r.html), but this one explains more how to query SDMX datasets using the ``REST`` SDMX web-services, which then restrains to some data providers. One important aspect of ``rsdmx`` is that it doesn't restrain to the SDMX REST **web-services** specifications, but only focuses on the SDMX **format** specifications. The reason is that they are still many institutions that do not offer REST web-services, implement adhoc services or just provide SDMX files to download. Large data requests sometimes also redirect to adhoc download facilities. Hence, because ``rsdmx`` focuses on the format (format abstraction library), it allows reading data that it would not be possible to if it would be a pure ``REST`` service interface. ``rsdmx`` can then read local SDMX` data as well.

As explained in my email to ROpenSci, i had initially no vignette because preparing one bigger, as article, that explains the package in detail. For the purpose of this submission, i've finally decided to create one ``quickstart``. Nevertheless, this quickstart yet shows the package in action with real-world data flows. I've included examples with:
* **remote** datasets: If you feel it would add to the overall understanding, I might add to the quickstart a brief indication how to query SDMX web-services, but again this is out of scope of rsdmx which is a low-level library for SDMX, and not an interface to SDMX web-services.
* **local** datasets (after a bulk download of SDMX files)
* **metadata** documents (that describe a particular dataset)

Now i see the quickstart section of the README and it is the initial one.. I will update it from the quickstart vignette which provides various examples.

Regarding ``data.frame`` mappings, they are several ``as.data.frame`` ``S3`` methods (see [NAMESPACE](https://github.com/opensdmx/rsdmx/blob/master/NAMESPACE#L80)) according to the ``SDMX*`` ``S4`` object being manipulated. In SDMX, they are several data sub-formats, but generally two main one: ``Generic`` and ``Compact``, the latter is derivate in other formats specific to the data provider. Each sub-format brings a ``S3method`` to coerce into ``data.frame``.
For metadata, ``as.data.frame`` is available to read ``codelists`` and ``concepts`` (_ie_ reference data).

**Comment by eblondel** [comment]
@jeroenooms 
* I've slightly improved the quickstart vignette https://github.com/opensdmx/rsdmx/blob/master/vignettes/quickstart.Rmd I've added a quick introduction to SDMX essentials, in order to familiarize with SDMX before jumping into the R part.
* i've also explained a bit more what ``rsdmx`` covers in term of functionality (focus on SDMX format vs. web-services API).
* i've also added a link to a short intro on SDMX which extends the quick intro provided in the vignette.
Hope this helps

**Comment by jeroenooms** [comment]
@eblondel I tried building the vignette and I get this: http://rpubs.com/jeroenooms/rsdmx-quickstart. Is that the intended output?

**Comment by eblondel** [comment]
@jeroenooms i've fixed the vignette. Thanks

**Comment by jeroenooms** [comment]
Ok so you added `eval=FALSE` but the examples is still broken? It gives a ton of warnings...

**Comment by eblondel** [comment]
I've added ``eval=FALSE`` indeed. Examples are NOT broken, they work. They would be broken with an ``error`` and a wrong result, not with a ``warning``. Anyway, i'm currently looking into the first set of warnings (only) to fix it since these particular warnings are unexpected, but it's not the case of all warnings. Is there  any way in RMarkdown to ``eval`` an example, and switch off ``warning`` (without calling ``invisible`` for sure)? I keep you update.

**Comment by eblondel** [comment]
@jeroenooms I've further tested the vignette with RStudio. As said, the ``warnings`` were not blocking, and examples are working. I've fixed the warnings anyway which i agree were annoying. I've let ``eval=FALSE`` for the ``install_github`` code (so ensure you update the package before running the vignette). Everything should be ok now.

**Comment by jeroenooms** [comment]
Those warnings usually indicate that there are bugs in concatenating vectors which might lead to the wrong data being inserted in the dataframe. I would much prefer if you try to find the origin of these warnings rather than muffle things under the carpet with `suppressWarnings`...

**Comment by eblondel** [comment]
I'm not "muffling things under the carpet", and if i've put a ``suppressWarnings``, it is because i found the origin of these warnings: observation status are not mandatory in SDMX, so some observations have, some other do not, I would not put a ``suppressWarnings`` if i would have a doubt or would not know the origin of it.

**Comment by eblondel** [comment]
Alternatively, i might use ``rbind.fill`` from ``plyr`` package (because it is yet a declared dependency), but IHMO it is not necessary here, a ``suppressWarnings`` is enough to deal with this case for which the origin is well-known.

**Comment by jeroenooms** [comment]
This warning always makes me very nervous, it is rarely ignorable. It means that you are combining data of incompatible dimensions and R is repeating a vector to fill things up. It would be much better practice if you can construct your data frame in such a way that it does not trigger this warning in the first place, rather than suppressing it.

**Comment by eblondel** [comment]
I understand your point. When i say that the origin is well-identified is because it deals with the standard SDMX-ML spec itself. In the compact data format (this what we are talking about), an ``observation`` comes with attributes, some are mandatory, some optional. This means that according to the ``observation`` you will not have the same number of ``XML`` attributes. One key point is that there is no clear statement about the naming of these attributes in the standard, which means that i cannot pre-build a ``data.frame`` looking for particular attribute ``names`` that are not known a priori. As said, an alternative not to use ``suppressWarnings`` is to use ``rbind.fill``.

**Comment by jeroenooms** [comment]
@eblondel do you happen to be at the french r meeting in grenoble this week?

**Comment by eblondel** [comment]
Hum, no, i was not aware of it, i'm currently on duty travel until next week. Are you going to attend?

**Comment by jeroenooms** [comment]
Yes I'm in Grenoble all week. Will you attend useR 2015 in Denmark?

**Comment by eblondel** [comment]
No, unfortunately :-(, i could attend to useR 2015 in Denmark. I know that some people (Rytis Bagdziunas) will talk about ``rsdmx`` in his poster named "Short-term forecasting with factor models".

**Comment by jeroenooms** [comment]
Okay thats good to know thank you

**Comment by jeroenooms** [comment]
Okay thats good to know, thank you. Do you know where I can find the `dynfactoR` package? Perhaps that will help me understand better how `rsdmx` is used in practice.

**Comment by eblondel** [comment]
The author is on [Github](https://github.com/rbagd?tab=repositories), but it seems ``dynfactorR`` is not available online (at least at now). You may contact him directly. Alternatively, you can also have a look to its repositories, where he put in place some use cases based on ``rsdmx``. See this one for example: [https://github.com/rbagd/eu-unemployment](https://github.com/rbagd/eu-unemployment) Hope this helps

**Comment by eblondel** [comment]
@jeroenooms If it helps, you can see https://github.com/rbagd/useR2015 (just found it, it is the poster i mentioned in some past comment).

I have also been informed of a nice use case using ``opencpu`` to build a SDMX viewer, explained in this post: https://medium.com/@ggruic/what-is-open-data-and-how-can-we-access-it-d47f0089e330 (see https://github.com/ggruic/sdmxquickview).

**Comment by jeroenooms** [comment]
I'll return from traveling tomorrow, then I'll have another look this week. Also I saw a poster at useR about  the `RJSDMX` package. Maybe you can discuss the differences with this package a bit as well.

**Comment by eblondel** [comment]
Thanks, as follow-up, i have improved a bit the code related to what we discussed (``warnings`` raised for compact data observation attributes). https://github.com/opensdmx/rsdmx/commit/5b6f91d37c312f3e5cc88588fb9ac92e99c1d075

For what concerns the main differences with RJSDMX, i've summarized them in this ticket description (see point 6). As initially explained to ropensci, I intend to add in the future another more technical vignette but in the form of paper, and it is planned to discuss rsdmx by comparing it further with other packages.

**Comment by sckott** [comment]
@eblondel Hows it going with changes in response to review?

**Comment by sckott** [comment]
@eblondel Hows it going with changes in response to review?

**Comment by eblondel** [comment]
Hi @sckott, i believe most of the changes requested have yet been tackled in the past, however at now i've put this rsdmx submission in stand-by, because i want to go deeper in evaluating pros/cons, and look how policies might evolve at short-medium term. Counting with your understanding, 
Best, Emmanuel

**Comment by sckott** [comment]
Thanks for the update

**Comment by sckott** [comment]
@eblondel Any updates on this? Anything we can help with?

**Comment by sckott** [comment]
@eblondel it's been over a year since we've heard from you, closing the issue, you are welcome to resubmit
